COINS = {
    'Bitcoin' : 'BTC',
    'Ethereum' : 'ETH',
    'Cardano' : 'ADA',
    'Ripple' : 'XRP',
    'Solana' : 'SOL',
    'Polkadot' : 'DOT',
    'Terra' : 'LUNA',
    'Uniswap' : 'UNI',
    'Avalanche' : 'AVAX',
    'Litecoin' : 'LTC',
    'Chainlink' : 'LINK',
    'Stellar' : 'XLM',
    'Axie Infinity' : 'AXS',
    'Tezos' : 'XTZ',
    'TRON' : 'TRX',
    'Cosmos' : 'ATOM',
    'Polygon' : 'MATIC',
    'Binance Coin' : 'BNB',
    'Dogecoin' : 'DOGE',    
    'Wrapped Bitcoin' : 'WBTC',    
    'Bitcoin Cash' : 'BCH',    
    'Algorand' : 'ALGO',    
    'SHIBA INU' : 'SHIBA',    
    'Filecoin' : 'FIL',
    'Internet Computer' : 'ICP',    
    'VeChain' : 'VET',    
    'TRON' : 'TRX',    
    'Ethereum Classic' : 'ETC',
    'THETA' : 'THETA',
    'Dai' : 'DAI',
    'Bitcoin BEP2' : 'BTCB',
    'Fantom' : 'FTM',
    'Hedera Hashgraph' : 'HBAR',
    'Monero' : 'XMR',
    'EOS' : 'EOS',
    'IOTA' : 'MIOTA',
    'Neo' : 'NEO',
    'Waves' : 'WAVES',
    'Dash' : 'DASH',
    'Zcash' : 'ZEC',
    'Basic Attention Token' : 'BAT',
    }