COINS = {
    'Bitcoin' : 'BTC',
    'Ethereum' : 'ETH',
    'Cardano' : 'ADA',
    'Ripple' : 'XRP',
    'Solana' : 'SOL',
    'Polkadot' : 'DOT',
    'Terra' : 'LUNA',
    'Uniswap' : 'UNI',
    'Avalanche' : 'AVAX',
    'Litecoin' : 'LTC',
    'Chainlink' : 'LINK',
    'Stellar' : 'XLM',
    'Axie Infinity' : 'AXS',
    'Tezos' : 'XTZ',
    'TRON' : 'TRX',
    'Cosmos' : 'ATOM',
    'Polygon' : 'MATIC',
    'Binance Coin' : 'BNB',
    'Dogecoin' : 'DOGE',    
    }